name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          git clone https://github.com/pret/agbcc.git
          cd agbcc 
          ./build.sh
          ./install.sh ../

      - name: Build
        run: make -j${nproc}

      - name: UK
        run: make -j${nproc} uk

      - name: Modern
        run: make -j${nproc} modern
